version: '3.8'

services:
  bookshelf-app:
    build:
      context: .
      dockerfile: BookShelf/Dockerfile.prod
    image: bookshelf-app:latest
    restart: always
    ports:
      - "80:8080"
      - "443:8081"
    # depends_on:
    #   - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Host=shinkansen.proxy.rlwy.net;Port=21882;Database=railway;Username=postgres;Password=wFnrSggmAnzRuSRRkWhzwciBSpdiWrYG;
    networks:
      - bookshelf-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # postgres-db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=BookShelfDb
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - bookshelf-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  bookshelf-network:
    driver: bridge

volumes:
  postgres-data: